version: "3"

services:

  # wsgi classwork
  backend:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    container_name: backend
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
      - memcached
    volumes:
      - ./:/srv/project
    ports:
      - "8000:8000"

  celery:
    build: .
    command: /bin/bash ./commands/start_celery.sh
    container_name: celery
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./:/srv/project

  celerybeat:
    build: .
    command: celery -A currency_exchange beat -l info --workdir=/srv/project/src
    container_name: celerybeat
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./:/srv/project

  rabbitmq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbitmq
    restart: always
    env_file:
      - .env
    ports:
      - "15672:15672"

  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always

#  celery:
#    image: celery:4.4.0
#    build: .
#    command: bash -c "cd ./src && celery -A currency_exchange worker -l info"
#    container_name: celery
#    volumes:
#      - .:/app
#    depends_on:
#      - postgres
#      - rabbitmq

#  celery-beat:
#    build: .
#    command: bash -c "cd ./src && celery -A currency_exchange beat -l INFO"
#    container_name: celery-beat
#    volumes:
#      - .:/app
#    depends_on:
#      - postgres
#      - rabbitmq

  postgres:
    image: postgres:11.3
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.17.4-alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

#  web:
#    build: .
#    command: python src/manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres

volumes:
  pgdata: {}


#{
#  "version": "3",
#  "services": [
#    {'rabbitmq': {'image': 'rabbitmq:3.8-rc-management'}}
#  ]
#}