# Generated by Django 2.2.10 on 2020-03-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_activationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='sms_code',
            field=models.IntegerField(default=784721, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=123456789, max_length=30),
            preserve_default=False,
        ),
    ]
