# Generated by Django 2.2.10 on 2020-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20200220_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Privat Bank'), (2, 'Mono Bank'), (3, 'Vkurse'), (4, 'Obmen'), (5, 'MTB Bank'), (6, 'Industrial Bank')]),
        ),
    ]
